# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='description',
        ),
        migrations.AddField(
            model_name='gift',
            name='image_link',
            field=models.URLField(default='http://google.com/', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(max_length=128),
        ),
    ]
