# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azsearch', '0002_auto_20180417_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='price_desc',
            field=models.CharField(default='$0.00', max_length=128),
            preserve_default=False,
        ),
    ]
