# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azsearch', '0003_auto_20180417_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='carts',
            field=models.ManyToManyField(to='azsearch.Cart'),
        ),
    ]
