# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azsearch', '0004_auto_20180511_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gender', 'gender'), ('age', 'age'), ('festival', 'festival')], max_length=30)),
                ('tag', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('0', '0-5'), ('5', '5-8'), ('8', '8-11'), ('11', '11-12'), ('12', '12-15'), ('15', '15-18'), ('18', '18-22'), ('22', '22-30'), ('30', '30-40'), ('40', '40+'), ('birthday', 'birthday'), ('christmas', 'christmas'), ('mother', 'christmas'), ('wedding', 'christmas')], max_length=30)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azsearch.Gift')),
            ],
        ),
    ]
