# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azsearch', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='carts',
        ),
        migrations.AddField(
            model_name='cart',
            name='gifts',
            field=models.ManyToManyField(to='azsearch.Gift'),
        ),
    ]
